--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/BlockData_Example_Plugin
build-by-default: true
branches:
- master
projects:
  BlockData_Example_Plugin:
    path: ""
    libs:
      - src: NhanAZ/BlockData/BlockData
        version: 0.0.1
...
